swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert(7)//
info:
  version: "1.0.0"
  title: XSS img
  description: <img src=x onerror=alert('XSS');> <img src=1 onerror=alert(1)> <svg onload=alert(1)// #"><img src=/ onerror=alert(2)>
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
