swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert(7)//
info:
  version: "1.0.0"
  title: XSS img 11111111111123999
  description: <h3>hello</h3>
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
